addSbtPlugin("com.eed3si9n" % "sbt-nocomma" % "0.1.1")
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "2.1.3")
addSbtPlugin("com.github.sbt" % "sbt-pgp" % "2.2.1")
addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.11.0")
addSbtPlugin("org.scalaxb" % "sbt-scalaxb" % "1.11.1")
